services:
  api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/realworld
    ports:
      - "80:80"
    networks:
      - realworld
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - realworld

  complexity-tests:
    build:
      dockerfile: dockerfile.dev
      context: .
    volumes:
      - ./:/app/
    entrypoint:
      ["/bin/sh", "-c", "poetry run wily build . && poetry run wily diff ."]
    profiles: [tests]

  unit-tests:
    build:
      dockerfile: dockerfile.dev
      context: .
    volumes:
      - ./:/app/
    entrypoint: ["poetry", "run", "pytest", "tests"]
    profiles: [tests]

  integration-tests:
    build:
      context: ./tests/integration
    environment:
      - APIURL=http://api:80
    depends_on:
      - api
    networks:
      - realworld
    profiles: [tests]

  pre-commit:
    build:
      dockerfile: dockerfile.dev
      context: .
    volumes:
      - ./:/app/
      - pre-commit:/root/.cache/pre-commit/
    entrypoint: ["poetry", "run", "pre-commit", "run", "--all-files"]
    profiles: [pre-commit]

volumes:
  pre-commit:
  mongodb:

networks:
  realworld:
    driver: bridge
