version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv run setup
          environment:
            PIPENV_VENV_IN_PROJECT: "true"

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run linting check
          command: |
            pipenv run lint
      - run:
          name: run tests
          command: |
            pipenv run coverage

      - codecov/upload:
          file: coverage.xml
